version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    command: >
      sh -c "cd /code/Deployment && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
